#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from fastapi.routing import APIRoute

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
OUT_FILE = ROOT / "docs" / "API_ENDPOINTS_GENERATED.md"


def auth_for_path(path: str) -> str:
    admin_read_paths = {"/admin/summary", "/admin/users", "/admin/activity", "/admin/billing-ledger"}
    if path in admin_read_paths:
        return "Admin (`x-admin-key` or admin `x-session-token`)"
    if path.startswith("/admin/"):
        return "Admin (`x-admin-key`)"
    if path in {"/catalog/upsert", "/catalog/import"}:
        return "Admin user (`x-session-token`)"
    if path == "/billing/webhook":
        return "Public (Stripe signature)"
    if path in {"/db/migrate", "/db/seed"}:
        return "Public (local/dev only)"
    if path in {"/health", "/auth/register", "/auth/login", "/pricing/llm/status", "/catalog/tree", "/catalog/search"}:
        return "Public"
    return "User (`x-session-token`)"


def group_for_path(path: str) -> str:
    if path.startswith("/auth") or path.startswith("/profile"):
        return "Auth/Profile"
    if path.startswith("/estimates"):
        return "Estimates"
    if path.startswith("/catalog"):
        return "Catalog"
    if path.startswith("/templates"):
        return "Templates"
    if path.startswith("/proposals"):
        return "Proposals"
    if path.startswith("/billing"):
        return "Billing"
    if path.startswith("/pricing/llm"):
        return "LLM Pricing"
    if path.startswith("/audit") or path.startswith("/activity"):
        return "Audit/Activity"
    if path.startswith("/backup"):
        return "Backup/Restore"
    if path.startswith("/admin"):
        return "Admin"
    return "Platform"


def render_markdown() -> str:
    if str(SRC_DIR) not in sys.path:
        sys.path.insert(0, str(SRC_DIR))
    from remodelator.interfaces.api.main import app  # pylint: disable=import-outside-toplevel

    rows: list[tuple[str, str, str, str, str]] = []
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        if not route.include_in_schema:
            continue
        for method in sorted(route.methods or []):
            if method not in {"GET", "POST", "PUT", "DELETE"}:
                continue
            path = route.path
            lifecycle = "Deprecated" if bool(route.deprecated) else "Active"
            rows.append((method, path, group_for_path(path), auth_for_path(path), lifecycle))
    rows.sort(key=lambda x: (x[2], x[1], x[0]))

    lines: list[str] = []
    lines.append("# API Endpoints (Generated)")
    lines.append("")
    lines.append("Source: FastAPI route registry (`remodelator.interfaces.api.main:app`)")
    lines.append("This file is generated by `scripts/generate_api_endpoints_doc.py`. Do not edit manually.")
    lines.append("")
    lines.append("| Method | Path | Domain | Auth | Lifecycle |")
    lines.append("|---|---|---|---|---|")
    for method, path, domain, auth, lifecycle in rows:
        lines.append(f"| {method} | `{path}` | {domain} | {auth} | {lifecycle} |")

    lines.append("")
    lines.append(f"Total endpoints: **{len(rows)}**")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API endpoint inventory markdown from FastAPI source.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if generated output matches docs/API_ENDPOINTS_GENERATED.md and exit non-zero on drift.",
    )
    args = parser.parse_args()

    rendered = render_markdown()
    if args.check:
        current = OUT_FILE.read_text() if OUT_FILE.exists() else ""
        if current != rendered:
            diff = "".join(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=str(OUT_FILE),
                    tofile="generated",
                )
            )
            sys.stderr.write("API endpoint docs are stale. Run `python3 scripts/generate_api_endpoints_doc.py`.\n")
            sys.stderr.write(diff)
            return 1
        return 0

    OUT_FILE.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
