import {
  DEFAULT_ADMIN_KEY,
  DEFAULT_DEMO_CHECKLIST,
  DEFAULT_LINE_ITEM_FORM,
  DEFAULT_PROFILE_FORM,
  DEFAULT_PROFILE_ROLE,
  DEFAULT_PROFILE_STATUS,
} from "./defaults";
import {
  decimalOrZero,
  formatCurrency,
  formatLlmStatus,
} from "./formatters";
import { createBillingActions } from "./billingActions";
import { createGuardedRunners } from "./guardedRunners";
import { useActionRunner } from "./useActionRunner";
import { createProposalActions } from "./proposalActions";
import { createAdminActions } from "./adminActions";
import { createTemplateActions } from "./templateActions";
import { createLlmActions } from "./llmActions";
import { createEstimateActions } from "./estimateActions";
import { createCatalogActions } from "./catalogActions";
import { createAuthActions } from "./authActions";
import { createWorkspaceActions } from "./workspaceActions";
import { createProfileActions } from "./profileActions";
import { createDataLoaders } from "./dataLoaders";
import { createAdminFilterBindings } from "./adminFilterBindings";
import { buildExternalBlockers, buildQuickstartCatalogNodes, isQuickstartCatalogReady } from "./appStatus";
import { clearWorkspaceState } from "./workspaceReset";
import { useSessionBootstrap } from "./useSessionBootstrap";
import { useEstimateSelectionSync } from "./useEstimateSelectionSync";
import { useWorkspaceForms } from "./useWorkspaceForms";
import { useProfileState } from "./useProfileState";
import { useSessionStorage } from "./useSessionStorage";
import { useCatalogState } from "./useCatalogState";
import { useOutputState } from "./useOutputState";
import { useAuthState } from "./useAuthState";
import { useLlmState } from "./useLlmState";
import { useWorkspaceCoreState } from "./useWorkspaceCoreState";

export function useAppController() {
  const { session, persistSession, adminKey, setAdminKey, persistAdminKey } = useSessionStorage(DEFAULT_ADMIN_KEY);
  const {
    registerEmail,
    setRegisterEmail,
    registerPassword,
    setRegisterPassword,
    registerName,
    setRegisterName,
    loginEmail,
    setLoginEmail,
    loginPassword,
    setLoginPassword,
  } = useAuthState();
  const {
    profileFullName,
    setProfileFullName,
    profileRole,
    setProfileRole,
    profileLaborRate,
    setProfileLaborRate,
    profileItemMarkupPct,
    setProfileItemMarkupPct,
    profileEstimateMarkupPct,
    setProfileEstimateMarkupPct,
    profileTaxRatePct,
    setProfileTaxRatePct,
    profileStatus,
    setProfileStatus,
    activitySummary,
    setActivitySummary,
    auditTrail,
    setAuditTrail,
    snapshotStatus,
    setSnapshotStatus,
    lastSnapshot,
    setLastSnapshot,
    resetProfileForm,
  } = useProfileState();

  const {
    estimateTitle,
    setEstimateTitle,
    estimateCustomerName,
    setEstimateCustomerName,
    estimateCustomerEmail,
    setEstimateCustomerEmail,
    estimateCustomerPhone,
    setEstimateCustomerPhone,
    estimateJobAddress,
    setEstimateJobAddress,
    estimateMarkupPct,
    setEstimateMarkupPct,
    estimateTaxRatePct,
    setEstimateTaxRatePct,
    quickstartCatalogNodeName,
    setQuickstartCatalogNodeName,
    quickstartMaxItems,
    setQuickstartMaxItems,
    lineItemName,
    setLineItemName,
    lineItemQty,
    setLineItemQty,
    lineItemUnitPrice,
    setLineItemUnitPrice,
    lineItemLaborHours,
    setLineItemLaborHours,
    lineItemMarkupPct,
    setLineItemMarkupPct,
    lineItemDiscountValue,
    setLineItemDiscountValue,
    lineItemDiscountIsPercent,
    setLineItemDiscountIsPercent,
    lineItemGroupName,
    setLineItemGroupName,
    editQuantity,
    setEditQuantity,
    editUnitPrice,
    setEditUnitPrice,
    editLaborHours,
    setEditLaborHours,
    editItemMarkupPct,
    setEditItemMarkupPct,
    editDiscountValue,
    setEditDiscountValue,
    editDiscountIsPercent,
    setEditDiscountIsPercent,
    editGroupName,
    setEditGroupName,
    lineGroupName,
    setLineGroupName,
    resetEstimateForm,
    resetLineItemForm,
    resetEditLineItemForm,
  } = useWorkspaceForms();

  const {
    llmStatus,
    setLlmStatus,
    llmReadyForLive,
    setLlmReadyForLive,
    llmBlockerReason,
    setLlmBlockerReason,
    llmContext,
    setLlmContext,
    llmSuggestedPrice,
    setLlmSuggestedPrice,
    llmSuggestion,
    setLlmSuggestion,
  } = useLlmState();

  const {
    catalogQuery,
    setCatalogQuery,
    catalogResults,
    setCatalogResults,
    catalogTree,
    setCatalogTree,
    catalogUpsertName,
    setCatalogUpsertName,
    catalogUpsertPrice,
    setCatalogUpsertPrice,
    catalogUpsertLabor,
    setCatalogUpsertLabor,
    catalogUpsertDescription,
    setCatalogUpsertDescription,
    catalogImportJson,
    setCatalogImportJson,
    catalogOpsOutput,
    setCatalogOpsOutput,
    templateName,
    setTemplateName,
    templates,
    setTemplates,
    selectedTemplateId,
    setSelectedTemplateId,
  } = useCatalogState();

  const {
    proposalPdfPath,
    setProposalPdfPath,
    proposalPdfResult,
    setProposalPdfResult,
    estimateExportPath,
    setEstimateExportPath,
    estimateExportResult,
    setEstimateExportResult,
    billingAmount,
    setBillingAmount,
    billingDetails,
    setBillingDetails,
    idempotencyKey,
    setIdempotencyKey,
    stripeCustomerEmail,
    setStripeCustomerEmail,
    stripeCardLast4,
    setStripeCardLast4,
    stripeSubscriptionId,
    setStripeSubscriptionId,
    stripeCancelReason,
    setStripeCancelReason,
    statusTarget,
    setStatusTarget,
    proposalPreview,
    setProposalPreview,
    billingResponse,
    setBillingResponse,
    billingPolicy,
    setBillingPolicy,
    billingProviderStatus,
    setBillingProviderStatus,
    subscriptionState,
    setSubscriptionState,
  } = useOutputState();

  const {
    estimates,
    setEstimates,
    selectedEstimateId,
    setSelectedEstimateId,
    selectedEstimate,
    setSelectedEstimate,
    selectedLineItemId,
    setSelectedLineItemId,
    billingLedger,
    setBillingLedger,
    adminResult,
    setAdminResult,
    adminFilters,
    setAdminFilters,
    activePanel,
    setActivePanel,
  } = useWorkspaceCoreState();
  const { busy, actionStatus, actionStatusIsError, logLines, pushLog, clearLogs, run } = useActionRunner();
  const adminFilterBindings = createAdminFilterBindings(setAdminFilters);

  const selectedLines = selectedEstimate?.line_items ?? [];
  const selectedLine = selectedLines.find((line) => line.id === selectedLineItemId) ?? null;
  const quickstartCatalogNodes = buildQuickstartCatalogNodes(catalogTree, quickstartCatalogNodeName);
  const quickstartCatalogReady = isQuickstartCatalogReady(catalogTree);
  const showLlmBlockerBanner = !llmReadyForLive && !llmStatus.toLowerCase().includes("loading");
  const llmBlockerMessage = llmBlockerReason.trim() || "OpenRouter is not ready for required LLM calls.";
  const billingBlockerMessage =
    billingProviderStatus && billingProviderStatus.provider === "stripe" && !billingProviderStatus.ready_for_live
      ? billingProviderStatus.blocker_reason?.trim() || "Stripe billing provider is not ready."
      : null;
  const demoChecklist = DEFAULT_DEMO_CHECKLIST;
  const externalBlockers = buildExternalBlockers({
    showLlmBlockerBanner,
    llmBlockerMessage,
    billingBlockerMessage,
  });
  const currentTotalLabel = selectedEstimate ? `Current total: $${formatCurrency(selectedEstimate.total)}` : "No estimate selected";

  const authHeaders = (): Record<string, string> => {
    if (!session) {
      return {};
    }
    return { "x-session-token": session.sessionToken };
  };
  const isSessionAdmin = (profileRole || session?.role || DEFAULT_PROFILE_ROLE) === "admin";

  const { runWithSession, runWithEstimate, runWithEstimateLine } = createGuardedRunners({
    isSessionReady: Boolean(session),
    selectedEstimateId,
    selectedLineItemId,
    pushLog,
    run,
    authHeaders,
  });

  const clearWorkspace = () => {
    clearWorkspaceState({
      setEstimates,
      setSelectedEstimateId,
      setSelectedEstimate,
      setSelectedLineItemId,
      resetEstimateForm,
      resetLineItemForm,
      resetEditLineItemForm,
      setProposalPreview,
      setBillingResponse,
      setBillingAmount,
      setBillingDetails,
      setIdempotencyKey,
      setStripeCustomerEmail,
      setStripeCardLast4,
      setStripeSubscriptionId,
      setStripeCancelReason,
      setBillingPolicy,
      setBillingProviderStatus,
      setSubscriptionState,
      setBillingLedger,
      setTemplates,
      setSelectedTemplateId,
      setProposalPdfResult,
      setEstimateExportResult,
      setLlmSuggestion,
      setLlmSuggestedPrice,
      setCatalogOpsOutput,
      setActivitySummary,
      setAuditTrail,
      setLastSnapshot: () => setLastSnapshot(null),
      setSnapshotStatus,
      setAdminResultNone: () => setAdminResult({ kind: "none" }),
    });
  };

  const {
    loadCatalogTree,
    loadLlmStatus,
    loadEstimates,
    loadEstimate,
    refreshEstimateViews,
    loadBillingLedger,
    loadBillingPolicy,
    loadBillingProviderStatus,
    loadSubscriptionState,
    loadTemplates,
    loadProfile,
    loadActivityAndAudit,
  } = createDataLoaders({
    isSessionReady: Boolean(session),
    authHeaders,
    setCatalogTree,
    setLlmStatus,
    setLlmReadyForLive,
    setLlmBlockerReason,
    formatLlmStatus,
    setEstimates,
    setSelectedEstimate,
    setSelectedEstimateId,
    setBillingLedger,
    setBillingPolicy,
    setBillingProviderStatus,
    setBillingAmount,
    setBillingDetails,
    setSubscriptionState,
    setTemplates,
    setSelectedTemplateId,
    setProfileFullName,
    setProfileRole,
    setProfileLaborRate,
    setProfileItemMarkupPct,
    setProfileEstimateMarkupPct,
    setProfileTaxRatePct,
    setProfileStatus,
    defaultProfileStatus: DEFAULT_PROFILE_STATUS,
    defaultProfileRole: DEFAULT_PROFILE_ROLE,
    setActivitySummary,
    setAuditTrail,
    clearWorkspace,
  });

  useEstimateSelectionSync({
    selectedEstimate,
    selectedLineItemId,
    selectedLine,
    defaultLineItemGroupName: DEFAULT_LINE_ITEM_FORM.groupName,
    setSelectedLineItemId,
    resetEditLineItemForm,
    setEditQuantity,
    setEditUnitPrice,
    setEditLaborHours,
    setEditItemMarkupPct,
    setEditDiscountValue,
    setEditDiscountIsPercent,
    setEditGroupName,
    setLineGroupName,
    setEstimateTitle,
    setEstimateCustomerName,
    setEstimateCustomerEmail,
    setEstimateCustomerPhone,
    setEstimateJobAddress,
    setEstimateMarkupPct,
    setEstimateTaxRatePct,
  });

  useSessionBootstrap({
    session,
    clearWorkspace,
    resetProfileForm,
    setActivePanel,
    loadCatalogTree,
    loadLlmStatus,
    loadBillingPolicy,
    loadBillingProviderStatus,
    loadEstimates,
    loadBillingLedger,
    loadSubscriptionState,
    loadTemplates,
    loadProfile,
    loadActivityAndAudit,
    pushLog,
  });

  const {
    onSimulateEstimateCharge,
    onSimulateSubscription,
    onSimulateRefund,
    onSimulateStripeCardAttach,
    onSimulateStripeCheckoutComplete,
    onSimulateStripeUsageCharge,
    onSimulateStripeInvoicePaid,
    onSimulateStripeInvoiceFailed,
    onSimulateStripeCancelSubscription,
  } = createBillingActions({
    runWithSession,
    runWithEstimate,
    billingAmount,
    billingDetails,
    idempotencyKey,
    stripeCustomerEmail,
    stripeCardLast4,
    stripeSubscriptionId,
    stripeCancelReason,
    loadBillingLedger,
    loadSubscriptionState,
    setBillingResponse,
    setActivePanel: (panel) => setActivePanel(panel),
  });

  const { onRenderProposal, onGenerateProposalPdf, onExportEstimateJson } = createProposalActions({
    runWithEstimate,
    proposalPdfPath,
    estimateExportPath,
    setProposalPreview,
    setProposalPdfResult,
    setProposalPdfPath,
    setEstimateExportResult,
    setEstimateExportPath,
    setActivePanel: (panel) => setActivePanel(panel),
  });

  const { onAdminRequest } = createAdminActions({
    run,
    adminKey,
    isSessionAdmin,
    adminFilters,
    authHeaders,
    persistAdminKey,
    setAdminResult,
    clearLogs,
    persistSession: (next) => persistSession(next),
    clearWorkspace,
    resetProfileForm,
    loadCatalogTree,
    pushLog,
  });

  const { onSaveTemplate, onApplyTemplate } = createTemplateActions({
    runWithEstimate,
    templateName,
    selectedTemplateId,
    pushLog,
    loadTemplates,
    refreshEstimateViews,
    setActivePanel: (panel) => setActivePanel(panel),
  });

  const { onSuggestLlm, onApplyLlmSuggestion } = createLlmActions({
    runWithSession,
    runWithEstimateLine,
    llmReadyForLive,
    llmBlockerReason,
    llmContext,
    llmSuggestedPrice,
    selectedLine: selectedLine ? { item_name: selectedLine.item_name, unit_price: selectedLine.unit_price } : null,
    pushLog,
    refreshEstimateViews,
    loadLlmStatus,
    setLlmSuggestedPrice,
    setLlmSuggestion,
  });

  const { onEstimateAction } = createEstimateActions({
    runWithEstimate,
    statusTarget,
    setSelectedEstimateId: (id) => setSelectedEstimateId(id),
    refreshEstimateViews,
  });

  const { onCatalogSearch, onAddCatalogItem, onCatalogUpsert, onCatalogImport } = createCatalogActions({
    run,
    runWithSession,
    runWithEstimate,
    catalogQuery,
    catalogUpsertName,
    catalogUpsertPrice,
    catalogUpsertLabor,
    catalogUpsertDescription,
    catalogImportJson,
    lineItemName,
    lineItemGroupName,
    profileItemMarkupPct,
    defaultLineItemGroupName: DEFAULT_LINE_ITEM_FORM.groupName,
    defaultProfileItemMarkupPct: DEFAULT_PROFILE_FORM.itemMarkupPct,
    setCatalogResults,
    setCatalogOpsOutput,
    loadCatalogTree,
    refreshEstimateViews,
    resetLineItemForm,
    setLineItemName,
    setLineItemUnitPrice,
    setLineItemQty,
    setLineItemLaborHours,
    setLineItemMarkupPct,
    setActivePanel: (panel) => setActivePanel(panel),
    decimalOrZero,
  });

  const { onRegister, onLogin, onLogout } = createAuthActions({
    run,
    registerEmail,
    registerPassword,
    registerName,
    loginEmail,
    loginPassword,
    persistSession,
    clearWorkspace,
    resetProfileForm,
    pushLog,
    setLoginEmail,
    setRegisterPassword,
    setLoginPassword,
  });

  const { onLoadProfile, onSaveProfile, onRefreshActivity, onExportSnapshot, onRestoreSnapshot } = createProfileActions({
    runWithSession,
    profileFullName,
    profileLaborRate,
    profileItemMarkupPct,
    profileEstimateMarkupPct,
    profileTaxRatePct,
    decimalOrZero,
    setProfileFullName,
    setProfileRole,
    setProfileLaborRate,
    setProfileItemMarkupPct,
    setProfileEstimateMarkupPct,
    setProfileTaxRatePct,
    setProfileStatus,
    loadProfile,
    loadActivityAndAudit,
    setLastSnapshot,
    setSnapshotStatus,
    lastSnapshot,
    refreshEstimateViews,
    selectedEstimateId,
    pushLog,
  });

  const {
    onCreateEstimate,
    onAddLineItem,
    onUpdateEstimateDetails,
    onApplyCatalogQuickstart,
    onUpdateSelectedLine,
    onRemoveSelectedLine,
    onReorderSelectedLine,
    onGroupLineItems,
  } = createWorkspaceActions({
    runWithSession,
    runWithEstimate,
    runWithEstimateLine,
    estimateTitle,
    estimateCustomerName,
    estimateCustomerEmail,
    estimateCustomerPhone,
    estimateJobAddress,
    estimateMarkupPct,
    estimateTaxRatePct,
    quickstartCatalogNodeName,
    quickstartMaxItems,
    lineItemName,
    lineItemQty,
    lineItemUnitPrice,
    lineItemLaborHours,
    lineItemMarkupPct,
    lineItemDiscountValue,
    lineItemDiscountIsPercent,
    lineItemGroupName,
    editQuantity,
    editUnitPrice,
    editLaborHours,
    editItemMarkupPct,
    editDiscountValue,
    editDiscountIsPercent,
    editGroupName,
    lineGroupName,
    selectedLineItemId,
    selectedLines,
    defaultLineItemGroupName: DEFAULT_LINE_ITEM_FORM.groupName,
    decimalOrZero,
    refreshEstimateViews,
    pushLog,
  });

  const sessionPanelProps = {
    busy,
    sessionEmail: session?.email ?? null,
    isSessionReady: Boolean(session),
    registerEmail,
    setRegisterEmail,
    registerPassword,
    setRegisterPassword,
    registerName,
    setRegisterName,
    loginEmail,
    setLoginEmail,
    loginPassword,
    setLoginPassword,
    onRegister,
    onLogin,
    onLogout,
    profileFullName,
    profileRole,
    setProfileFullName,
    profileLaborRate,
    setProfileLaborRate,
    profileItemMarkupPct,
    setProfileItemMarkupPct,
    profileEstimateMarkupPct,
    setProfileEstimateMarkupPct,
    profileTaxRatePct,
    setProfileTaxRatePct,
    profileStatus,
    activitySummary,
    auditTrail,
    snapshotStatus,
    onLoadProfile,
    onSaveProfile,
    onRefreshActivity,
    onExportSnapshot,
    onRestoreSnapshot,
  };

  const workspacePanelProps = {
    busy,
    isSessionReady: Boolean(session),
    estimates,
    selectedEstimateId,
    selectedEstimate,
    selectedLines,
    selectedLineItemId,
    setSelectedLineItemId,
    estimateTitle,
    setEstimateTitle,
    estimateCustomerName,
    setEstimateCustomerName,
    estimateCustomerEmail,
    setEstimateCustomerEmail,
    estimateCustomerPhone,
    setEstimateCustomerPhone,
    estimateJobAddress,
    setEstimateJobAddress,
    estimateMarkupPct,
    setEstimateMarkupPct,
    estimateTaxRatePct,
    setEstimateTaxRatePct,
    quickstartCatalogNodeName,
    setQuickstartCatalogNodeName,
    quickstartMaxItems,
    setQuickstartMaxItems,
    quickstartCatalogNodes,
    quickstartCatalogReady,
    onCreateEstimate,
    onSelectEstimate: (estimateId: string) => void run("Select estimate", () => loadEstimate(estimateId)),
    onUpdateEstimateDetails,
    onApplyCatalogQuickstart,
    lineItemName,
    setLineItemName,
    lineItemQty,
    setLineItemQty,
    lineItemUnitPrice,
    setLineItemUnitPrice,
    lineItemLaborHours,
    setLineItemLaborHours,
    lineItemMarkupPct,
    setLineItemMarkupPct,
    lineItemDiscountValue,
    setLineItemDiscountValue,
    lineItemDiscountIsPercent,
    setLineItemDiscountIsPercent,
    lineItemGroupName,
    setLineItemGroupName,
    onAddLineItem,
    editQuantity,
    setEditQuantity,
    editUnitPrice,
    setEditUnitPrice,
    editLaborHours,
    setEditLaborHours,
    editItemMarkupPct,
    setEditItemMarkupPct,
    editDiscountValue,
    setEditDiscountValue,
    editDiscountIsPercent,
    setEditDiscountIsPercent,
    editGroupName,
    setEditGroupName,
    onUpdateSelectedLine,
    onRemoveSelectedLine,
    onReorderSelectedLine,
    lineGroupName,
    setLineGroupName,
    onGroupLineItems,
    llmStatus,
    llmReadyForLive,
    llmBlockerReason,
    onRefreshLlmStatus: () => void run("Refresh LLM status", loadLlmStatus),
    llmContext,
    setLlmContext,
    llmSuggestedPrice,
    setLlmSuggestedPrice,
    llmSuggestion,
    onSuggestLlm,
    onApplyLlmSuggestion,
    statusTarget,
    setStatusTarget,
    onEstimateAction,
  };

  const catalogPanelProps = {
    busy,
    isSessionReady: Boolean(session),
    hasSelectedEstimate: Boolean(selectedEstimateId),
    catalogQuery,
    setCatalogQuery,
    onCatalogSearch,
    onReloadCatalogTree: () => void run("Reload catalog tree", loadCatalogTree),
    catalogUpsertName,
    setCatalogUpsertName,
    catalogUpsertPrice,
    setCatalogUpsertPrice,
    catalogUpsertLabor,
    setCatalogUpsertLabor,
    catalogUpsertDescription,
    setCatalogUpsertDescription,
    onCatalogUpsert,
    catalogImportJson,
    setCatalogImportJson,
    onCatalogImport,
    catalogOpsOutput,
    catalogResults,
    onAddCatalogItem,
    catalogTree,
    templateName,
    setTemplateName,
    onSaveTemplate,
    selectedTemplateId,
    setSelectedTemplateId,
    templates,
    onApplyTemplate,
    estimateExportPath,
    setEstimateExportPath,
    onExportEstimateJson,
    estimateExportResult,
    proposalPdfPath,
    setProposalPdfPath,
    onGenerateProposalPdf,
    proposalPdfResult,
  };

  const outputPanelProps = {
    busy,
    isSessionReady: Boolean(session),
    hasSelectedEstimate: Boolean(selectedEstimateId),
    billingAmount,
    setBillingAmount,
    billingDetails,
    setBillingDetails,
    idempotencyKey,
    setIdempotencyKey,
    stripeCustomerEmail,
    setStripeCustomerEmail,
    stripeCardLast4,
    setStripeCardLast4,
    stripeSubscriptionId,
    setStripeSubscriptionId,
    stripeCancelReason,
    setStripeCancelReason,
    billingPolicy,
    billingProviderStatus,
    subscriptionState,
    billingResponse,
    billingLedger,
    proposalPreview,
    onRenderProposal,
    onSimulateEstimateCharge,
    onSimulateSubscription,
    onSimulateRefund,
    onSimulateStripeCardAttach,
    onSimulateStripeCheckoutComplete,
    onSimulateStripeUsageCharge,
    onSimulateStripeInvoicePaid,
    onSimulateStripeInvoiceFailed,
    onSimulateStripeCancelSubscription,
    onRefreshLedger: () =>
      void run("Refresh billing views", async () => {
        await Promise.all([loadBillingLedger(), loadSubscriptionState(), loadBillingProviderStatus()]);
      }),
  };

  const adminPanelProps = {
    busy,
    sessionEmail: session?.email ?? null,
    isSessionAdmin,
    adminKey,
    setAdminKey,
    adminFilters,
    ...adminFilterBindings,
    adminResult,
    logLines,
    demoChecklist,
    externalBlockers,
    onAdminRequest,
  };

  return {
    activePanel,
    setActivePanel,
    heroProps: {
      sessionEmail: session?.email ?? null,
      estimatesCount: estimates.length,
      currentTotalLabel,
      actionStatus,
      actionStatusIsError,
      llmBlockerMessage: showLlmBlockerBanner ? llmBlockerMessage : null,
      billingBlockerMessage,
    },
    sessionPanelProps,
    workspacePanelProps,
    catalogPanelProps,
    outputPanelProps,
    adminPanelProps,
  };
}
